# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31fd6861ae1a5061802af54b472726c741edd64f310b21c02a1348e7567b0156dad4f4ff4b87d99510ab6fe4e4017142e1d002d875b4c7f2304527f685060790

test:
  secret_key_base: d9fe7f14044512ce522c2d3b5659b7602c5617a3128ce32ca6e682504bdc58edea2b37afa0bff34033c462a62f40594f04e528b592bdc98eead6403ab6c5f6a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
